install.packages("dplyr",dependencies = T)
install.packages("tidyverse",dependencies = T)
install.packages("readr",dependencies = T)
install.packages("stringr",dependencies = T)
install.packages("tidyr",dependencies = T)
install.packages("ggplot2",dependencies = T)
install.packages('rmarkdown')
install.packages("tinytex", dependencies=T)
tinytex::install_tinytex()